// Los quince clubes de la Liga Americana.
// Los datos de franquicia son reales; los lideres y la tabla de anotacion van
// marcados como SIMULADO en pantalla, tal como pide la rubrica para el prototipo.

function franquicia(equipo) {
  return [
    { name: 'SERIES GANADAS', value: equipo.titles, unidad: 'TÍTULOS' },
    { name: 'BANDERINES', value: equipo.banners, unidad: 'BANDERINES' },
    { name: 'TEMPORADAS', value: 2026 - equipo.founded, unidad: 'AÑOS' },
  ]
}

const clubes = [
  {
    id: 'yankees',
    name: 'YANKEES',
    abbreviation: 'NY',
    tone: 'navy',
    region: 'ESTE',
    titles: 27,
    banners: 41,
    firstTitle: 1923,
    stadium: 'YANKEE STADIUM',
    city: 'BRONX',
    founded: 1901,
    history: 'Nacieron en Baltimore como Orioles en 1901 y se mudaron a Nueva York dos años después. La llegada de Babe Ruth en 1920 los convirtió en la franquicia dominante del siglo, con una racha de cinco títulos seguidos entre 1949 y 1953.',
    serie: { titulo: 'SERIE MUNDIAL 1996 · JUEGO 6', local: { abreviatura: 'NYY', entradas: [0, 0, 3, 0, 0, 0, 0, 0, '-'] }, visitante: { abreviatura: 'ATL', entradas: [0, 0, 1, 0, 0, 0, 0, 0, 1] } },
    bateo: [{ name: 'BABE RUTH', value: 659 }, { name: 'MICKEY MANTLE', value: 536 }, { name: 'LOU GEHRIG', value: 493 }],
    pitcheo: [{ name: 'WHITEY FORD', value: 236 }, { name: 'RED RUFFING', value: 231 }, { name: 'ANDY PETTITTE', value: 219 }],
  },
  {
    id: 'red-sox',
    name: 'RED SOX',
    abbreviation: 'B',
    tone: 'red',
    region: 'ESTE',
    titles: 9,
    banners: 14,
    firstTitle: 1903,
    stadium: 'FENWAY PARK',
    city: 'BOSTON',
    founded: 1901,
    history: 'Ganaron la primera Serie Mundial moderna en 1903 y después pasaron ochenta y seis años sin volver a levantarla. Fenway Park, abierto en 1912, es el parque más antiguo que sigue en uso en Grandes Ligas.',
    serie: { titulo: 'SERIE MUNDIAL 1975 · JUEGO 6', local: { abreviatura: 'BOS', entradas: [0, 0, 3, 0, 0, 0, 0, 0, 1] }, visitante: { abreviatura: 'CIN', entradas: [0, 0, 0, 0, 0, 3, 0, 0, 0] } },
    bateo: [{ name: 'TED WILLIAMS', value: 521 }, { name: 'DAVID ORTIZ', value: 483 }, { name: 'CARL YASTRZEMSKI', value: 452 }],
    pitcheo: [{ name: 'ROGER CLEMENS', value: 192 }, { name: 'CY YOUNG', value: 192 }, { name: 'TIM WAKEFIELD', value: 186 }],
  },
  {
    id: 'blue-jays',
    name: 'BLUE JAYS',
    abbreviation: 'TOR',
    tone: 'navy',
    region: 'ESTE',
    titles: 2,
    banners: 2,
    firstTitle: 1992,
    stadium: 'ROGERS CENTRE',
    city: 'TORONTO',
    founded: 1977,
    history: 'El único club fuera de Estados Unidos que ha ganado la Serie Mundial, y lo hizo dos veces seguidas en 1992 y 1993. La segunda la cerró Joe Carter con un jonrón en el sexto juego.',
    serie: { titulo: 'SERIE MUNDIAL 1993 · JUEGO 6', local: { abreviatura: 'TOR', entradas: [3, 0, 0, 0, 0, 1, 0, 0, 4] }, visitante: { abreviatura: 'PHI', entradas: [0, 0, 0, 1, 1, 0, 5, 0, 0] } },
    bateo: [{ name: 'CARLOS DELGADO', value: 336 }, { name: 'JOSÉ BAUTISTA', value: 288 }, { name: 'VERNON WELLS', value: 223 }],
    pitcheo: [{ name: 'DAVE STIEB', value: 175 }, { name: 'JIMMY KEY', value: 116 }, { name: 'ROY HALLADAY', value: 148 }],
  },
  {
    id: 'rays',
    name: 'RAYS',
    abbreviation: 'TB',
    tone: 'navy',
    region: 'ESTE',
    titles: 0,
    banners: 2,
    firstTitle: null,
    stadium: 'TROPICANA FIELD',
    city: 'ST. PETERSBURG',
    founded: 1998,
    history: 'La franquicia más joven de la liga. Después de una década en el sótano, llegaron a la Serie Mundial en 2008 y volvieron en 2020, siempre con una de las nóminas más bajas del béisbol.',
    serie: { titulo: 'SERIE MUNDIAL 2020 · JUEGO 4', local: { abreviatura: 'TB', entradas: [0, 1, 1, 0, 2, 0, 1, 1, 2] }, visitante: { abreviatura: 'LAD', entradas: [0, 2, 0, 2, 0, 1, 0, 2, 0] } },
    bateo: [{ name: 'EVAN LONGORIA', value: 261 }, { name: 'CARL CRAWFORD', value: 104 }, { name: 'BEN ZOBRIST', value: 114 }],
    pitcheo: [{ name: 'JAMES SHIELDS', value: 87 }, { name: 'DAVID PRICE', value: 82 }, { name: 'CHRIS ARCHER', value: 61 }],
  },
  {
    id: 'orioles',
    name: 'ORIOLES',
    abbreviation: 'BAL',
    tone: 'orange',
    region: 'ESTE',
    titles: 3,
    banners: 7,
    firstTitle: 1966,
    stadium: 'ORIOLE PARK',
    city: 'BALTIMORE',
    founded: 1901,
    history: 'Llegaron a Baltimore en 1954 y en los años sesenta y setenta armaron uno de los mejores equipos defensivos de la historia. Cal Ripken Jr. jugó 2,632 juegos seguidos, un récord que nadie se acerca a romper.',
    serie: { titulo: 'SERIE MUNDIAL 1983 · JUEGO 5', local: { abreviatura: 'BAL', entradas: [0, 0, 2, 0, 1, 0, 2, 0, '-'] }, visitante: { abreviatura: 'PHI', entradas: [0, 0, 0, 0, 0, 0, 0, 0, 0] } },
    bateo: [{ name: 'CAL RIPKEN JR.', value: 431 }, { name: 'EDDIE MURRAY', value: 343 }, { name: 'BOOG POWELL', value: 303 }],
    pitcheo: [{ name: 'JIM PALMER', value: 268 }, { name: 'MIKE CUELLAR', value: 143 }, { name: 'DAVE McNALLY', value: 181 }],
  },
  {
    id: 'guardians',
    name: 'GUARDIANS',
    abbreviation: 'CLE',
    tone: 'red',
    region: 'CENTRAL',
    titles: 2,
    banners: 6,
    firstTitle: 1920,
    stadium: 'PROGRESSIVE FIELD',
    city: 'CLEVELAND',
    founded: 1901,
    history: 'Ganaron en 1920 y 1948 y desde entonces cargan una de las sequías más largas del béisbol. Cambiaron de nombre en 2021, tras más de un siglo como Indios.',
    serie: { titulo: 'SERIE MUNDIAL 2016 · JUEGO 7', local: { abreviatura: 'CLE', entradas: [0, 0, 0, 0, 2, 1, 0, 3, 0] }, visitante: { abreviatura: 'CHC', entradas: [1, 0, 0, 2, 2, 0, 0, 1, 0] } },
    bateo: [{ name: 'JIM THOME', value: 337 }, { name: 'ALBERT BELLE', value: 242 }, { name: 'MANNY RAMÍREZ', value: 236 }],
    pitcheo: [{ name: 'BOB FELLER', value: 266 }, { name: 'MEL HARDER', value: 223 }, { name: 'EARLY WYNN', value: 164 }],
  },
  {
    id: 'tigers',
    name: 'TIGERS',
    abbreviation: 'DET',
    tone: 'navy',
    region: 'CENTRAL',
    titles: 4,
    banners: 11,
    firstTitle: 1935,
    stadium: 'COMERICA PARK',
    city: 'DETROIT',
    founded: 1901,
    history: 'Ty Cobb definió su primera era y Al Kaline la segunda. El título de 1968 llegó en un año difícil para la ciudad, y el de 1984 lo consiguieron arrancando la temporada con 35 victorias en 40 juegos.',
    serie: { titulo: 'SERIE MUNDIAL 1984 · JUEGO 5', local: { abreviatura: 'DET', entradas: [3, 0, 0, 0, 1, 0, 0, 4, '-'] }, visitante: { abreviatura: 'SD', entradas: [0, 0, 1, 4, 0, 0, 0, 0, 0] } },
    bateo: [{ name: 'AL KALINE', value: 399 }, { name: 'NORM CASH', value: 373 }, { name: 'MIGUEL CABRERA', value: 391 }],
    pitcheo: [{ name: 'HOOKS DAUSS', value: 223 }, { name: 'JUSTIN VERLANDER', value: 183 }, { name: 'MICKEY LOLICH', value: 207 }],
  },
  {
    id: 'royals',
    name: 'ROYALS',
    abbreviation: 'KC',
    tone: 'navy',
    region: 'CENTRAL',
    titles: 2,
    banners: 4,
    firstTitle: 1985,
    stadium: 'KAUFFMAN STADIUM',
    city: 'KANSAS CITY',
    founded: 1969,
    history: 'George Brett los llevó al título de 1985 tras remontar dos series desde abajo. Volvieron a ganar en 2015 con un equipo construido sobre defensa y bullpen, no sobre jonrones.',
    serie: { titulo: 'SERIE MUNDIAL 2015 · JUEGO 5', local: { abreviatura: 'NYM', entradas: [0, 0, 0, 0, 0, 1, 0, 0, 1] }, visitante: { abreviatura: 'KC', entradas: [0, 0, 0, 0, 0, 0, 0, 0, 2] } },
    bateo: [{ name: 'GEORGE BRETT', value: 317 }, { name: 'SALVADOR PÉREZ', value: 246 }, { name: 'MIKE SWEENEY', value: 197 }],
    pitcheo: [{ name: 'PAUL SPLITTORFF', value: 166 }, { name: 'DENNIS LEONARD', value: 144 }, { name: 'KEVIN APPIER', value: 115 }],
  },
  {
    id: 'twins',
    name: 'TWINS',
    abbreviation: 'MIN',
    tone: 'navy',
    region: 'CENTRAL',
    titles: 3,
    banners: 6,
    firstTitle: 1924,
    stadium: 'TARGET FIELD',
    city: 'MINNEAPOLIS',
    founded: 1901,
    history: 'Empezaron como Senadores de Washington y se mudaron a Minnesota en 1961. El séptimo juego de 1991, que Jack Morris lanzó completo por diez entradas sin permitir carrera, es de los mejores que se han jugado.',
    serie: { titulo: 'SERIE MUNDIAL 1991 · JUEGO 7', local: { abreviatura: 'MIN', entradas: [0, 0, 0, 0, 0, 0, 0, 0, 0] }, visitante: { abreviatura: 'ATL', entradas: [0, 0, 0, 0, 0, 0, 0, 0, 0] } },
    bateo: [{ name: 'HARMON KILLEBREW', value: 559 }, { name: 'KIRBY PUCKETT', value: 207 }, { name: 'JOE MAUER', value: 143 }],
    pitcheo: [{ name: 'WALTER JOHNSON', value: 417 }, { name: 'JIM KAAT', value: 190 }, { name: 'BERT BLYLEVEN', value: 149 }],
  },
  {
    id: 'white-sox',
    name: 'WHITE SOX',
    abbreviation: 'CWS',
    tone: 'navy',
    region: 'CENTRAL',
    titles: 3,
    banners: 6,
    firstTitle: 1906,
    stadium: 'RATE FIELD',
    city: 'CHICAGO',
    founded: 1901,
    history: 'El escándalo de 1919, cuando ocho jugadores fueron expulsados de por vida, marcó a la franquicia durante décadas. La sequía terminó en 2005 con una barrida en la Serie Mundial.',
    serie: { titulo: 'SERIE MUNDIAL 2005 · JUEGO 4', local: { abreviatura: 'HOU', entradas: [0, 0, 0, 0, 0, 0, 0, 0, 0] }, visitante: { abreviatura: 'CWS', entradas: [0, 0, 0, 0, 0, 0, 0, 1, 0] } },
    bateo: [{ name: 'FRANK THOMAS', value: 448 }, { name: 'PAUL KONERKO', value: 432 }, { name: 'HAROLD BAINES', value: 221 }],
    pitcheo: [{ name: 'TED LYONS', value: 260 }, { name: 'RED FABER', value: 254 }, { name: 'BILLY PIERCE', value: 186 }],
  },
  {
    id: 'astros',
    name: 'ASTROS',
    abbreviation: 'HOU',
    tone: 'orange',
    region: 'OESTE',
    titles: 2,
    banners: 5,
    firstTitle: 2017,
    stadium: 'DAIKIN PARK',
    city: 'HOUSTON',
    founded: 1962,
    history: 'Nacieron como Colt .45s y cambiaron de nombre en 1965, cuando estrenaron el Astrodome. Pasaron a la Liga Americana en 2013 y ganaron su primer título en 2017, tras una reconstrucción total.',
    serie: { titulo: 'SERIE MUNDIAL 2017 · JUEGO 5', local: { abreviatura: 'HOU', entradas: [4, 0, 0, 4, 0, 0, 3, 0, 2] }, visitante: { abreviatura: 'LAD', entradas: [0, 0, 4, 0, 3, 0, 4, 0, 1] } },
    bateo: [{ name: 'JEFF BAGWELL', value: 449 }, { name: 'LANCE BERKMAN', value: 326 }, { name: 'JOSÉ ALTUVE', value: 245 }],
    pitcheo: [{ name: 'JOE NIEKRO', value: 144 }, { name: 'ROY OSWALT', value: 143 }, { name: 'LARRY DIERKER', value: 137 }],
  },
  {
    id: 'angels',
    name: 'ANGELS',
    abbreviation: 'LAA',
    tone: 'red',
    region: 'OESTE',
    titles: 1,
    banners: 1,
    firstTitle: 2002,
    stadium: 'ANGEL STADIUM',
    city: 'ANAHEIM',
    founded: 1961,
    history: 'Tardaron cuarenta y un años en llegar a una Serie Mundial y la ganaron a la primera, en 2002, remontando desde abajo en el sexto juego. Mike Trout jugó ahí toda su carrera.',
    serie: { titulo: 'SERIE MUNDIAL 2002 · JUEGO 6', local: { abreviatura: 'ANA', entradas: [0, 0, 0, 0, 0, 3, 3, 0, '-'] }, visitante: { abreviatura: 'SF', entradas: [0, 0, 0, 0, 1, 0, 4, 0, 0] } },
    bateo: [{ name: 'MIKE TROUT', value: 378 }, { name: 'TIM SALMON', value: 299 }, { name: 'GARRET ANDERSON', value: 272 }],
    pitcheo: [{ name: 'CHUCK FINLEY', value: 165 }, { name: 'JERED WEAVER', value: 150 }, { name: 'NOLAN RYAN', value: 138 }],
  },
  {
    id: 'athletics',
    name: 'ATHLETICS',
    abbreviation: 'ATH',
    tone: 'green',
    region: 'OESTE',
    titles: 9,
    banners: 15,
    firstTitle: 1910,
    stadium: 'SUTTER HEALTH PARK',
    city: 'SACRAMENTO',
    founded: 1901,
    history: 'Han ganado en tres ciudades distintas: Filadelfia, Kansas City y Oakland. Ganaron tres Series seguidas entre 1972 y 1974, y en 2002 inventaron el Moneyball con la nómina más baja de la liga.',
    serie: { titulo: 'SERIE MUNDIAL 1989 · JUEGO 4', local: { abreviatura: 'SF', entradas: [0, 0, 0, 0, 0, 2, 0, 2, 0] }, visitante: { abreviatura: 'OAK', entradas: [1, 3, 0, 0, 0, 2, 2, 0, 1] } },
    bateo: [{ name: 'JIMMIE FOXX', value: 302 }, { name: 'MARK McGWIRE', value: 363 }, { name: 'REGGIE JACKSON', value: 269 }],
    pitcheo: [{ name: 'EDDIE PLANK', value: 284 }, { name: 'LEFTY GROVE', value: 195 }, { name: 'CATFISH HUNTER', value: 161 }],
  },
  {
    id: 'mariners',
    name: 'MARINERS',
    abbreviation: 'SEA',
    tone: 'navy',
    region: 'OESTE',
    titles: 0,
    banners: 0,
    firstTitle: null,
    stadium: 'T-MOBILE PARK',
    city: 'SEATTLE',
    founded: 1977,
    history: 'El único club que nunca ha llegado a una Serie Mundial. En 2001 ganaron 116 juegos, récord empatado de la era moderna, y aun así se quedaron fuera. Ken Griffey Jr. e Ichiro pasaron por aquí.',
    serie: { titulo: 'SERIE DIVISIONAL 1995 · JUEGO 5', local: { abreviatura: 'SEA', entradas: [0, 0, 1, 1, 0, 2, 0, 0, 2] }, visitante: { abreviatura: 'NYY', entradas: [0, 0, 0, 2, 0, 0, 0, 1, 2] } },
    bateo: [{ name: 'KEN GRIFFEY JR.', value: 417 }, { name: 'EDGAR MARTÍNEZ', value: 309 }, { name: 'JAY BUHNER', value: 307 }],
    pitcheo: [{ name: 'FÉLIX HERNÁNDEZ', value: 169 }, { name: 'JAMIE MOYER', value: 145 }, { name: 'RANDY JOHNSON', value: 130 }],
  },
  {
    id: 'rangers',
    name: 'RANGERS',
    abbreviation: 'TEX',
    tone: 'navy',
    region: 'OESTE',
    titles: 1,
    banners: 3,
    firstTitle: 2023,
    stadium: 'GLOBE LIFE FIELD',
    city: 'ARLINGTON',
    founded: 1961,
    history: 'Perdieron dos Series seguidas en 2010 y 2011, la segunda a un strike de ganarla. El título llegó por fin en 2023, ganando los once juegos que disputaron como visitantes en la postemporada.',
    serie: { titulo: 'SERIE MUNDIAL 2023 · JUEGO 5', local: { abreviatura: 'ARI', entradas: [0, 0, 0, 0, 0, 0, 0, 0, 0] }, visitante: { abreviatura: 'TEX', entradas: [0, 0, 0, 0, 0, 0, 1, 0, 4] } },
    bateo: [{ name: 'JUAN GONZÁLEZ', value: 372 }, { name: 'RAFAEL PALMEIRO', value: 321 }, { name: 'IVÁN RODRÍGUEZ', value: 217 }],
    pitcheo: [{ name: 'CHARLIE HOUGH', value: 139 }, { name: 'KENNY ROGERS', value: 133 }, { name: 'FERGIE JENKINS', value: 93 }],
  },
]

export const teams = clubes.map((club) => ({
  ...club,
  lideres: {
    BATEO: club.bateo.map((lider) => ({ ...lider, unidad: 'JONRONES' })),
    PITCHEO: club.pitcheo.map((lider) => ({ ...lider, unidad: 'GANADOS' })),
    FRANQUICIA: franquicia(club),
  },
}))

export const regions = ['TODAS', 'ESTE', 'OESTE', 'CENTRAL']
